"""Constants for the ForgeGuard demo application simulation indicators.

Defined once here so that every endpoint, schema, and test that needs the
disclaimer text imports from a single source of truth — preventing drift
between response fields.
"""

from __future__ import annotations

#: Shown on every demo API response to prevent confusion with real data.
SIMULATION_DISCLAIMER: str = (
    "This data is generated by the ForgeGuard demo application. "
    "No real financial transactions or payment credentials are involved."
)

#: Literal classification tag carried on all demo responses.
DATA_CLASSIFICATION_SIMULATED: str = "simulated"
